Unified approach to metrics
attestantio/vouch pull request #235
Opened 2024-08-17 16:03 UTC by Bez625

2024-08-18 18:13 UTC, mcdee commented
Please can you rebase this against current master and I'll take a look?  Thanks.

2024-08-18 18:29 UTC, Bez625 commented
> Please can you rebase this against current master and I'll take a look? Thanks.

Done! Thanks

2024-08-19 06:54 UTC, mcdee requested changes
Apologies for the delay in reviewing this, a few items.

2024-08-19 06:54 UTC, mcdee commented on services/attestationaggregator/standard/parameters.go
> +func WithChainTimeService(service chaintime.Service) Parameter {
We should ensure that this is non-null in `parseAndCheckParameters`

2024-08-19 06:54 UTC, mcdee commented on services/attestationaggregator/standard/metrics.go
> +func monitorAttestationAggregationCompleted(started time.Time, slot phase0.Slot, result string, chainTime chaintime.Service) {
I'm not a big fan of passing the service around in function calls.  It makes more sense to pass in either `startOfSlot` or `slotElapsed` as a variable here (and elsewhere this happens).

2024-08-19 17:07 UTC, mcdee requested changes
One minor tidy-up and I think we're good to go.

2024-08-19 17:07 UTC, mcdee commented on services/attestationaggregator/standard/service.go
> +		monitorAttestationAggregationCompleted(started, 0, "failed", startOfSlot)
`startOfSlot` here can be replaced with a simple `0`.

2024-08-19 17:07 UTC, mcdee commented on services/attester/standard/attest.go
> +		// No duty so using 0 values for monitoring.
As per previous comment.

2024-08-19 17:07 UTC, mcdee commented on services/synccommitteemessenger/standard/service.go
> +		startOfSlot := s.chainTimeService.StartOfSlot(0)
As per previous comment.

2024-08-20 09:22 UTC, mcdee approved these changes

2024-08-20 09:23 UTC, merged